import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import SeoLanding from '../../SeoLanding';

type Guide={title:string;description:string;intro:string;sections:{heading:string;body:string}[];faq?:{q:string;a:string}[]};

const guides:Record<string,Guide>={
'how-many-miles-is-10000-steps':{title:'How Many Miles Is 10,000 Steps?',description:'Learn how many miles 10,000 steps usually equals and why stride length changes the answer.',intro:'For many adults, 10,000 steps is roughly 4 to 5 miles, but your actual distance depends mainly on stride length.',sections:[{heading:'The quick answer',body:'A common rule of thumb puts 10,000 steps at about 4 to 5 miles. Taller walkers and longer strides generally cover more distance in the same number of steps.'},{heading:'Why the number varies',body:'Step length changes with height, walking speed, terrain and individual gait. A personal tracker or measured route gives a better estimate than a universal conversion.'},{heading:'Steps versus a 10K distance',body:'10,000 steps is not the same thing as a 10-kilometre race. PlanetHike uses the step target because it is simple and accessible, not because it represents an exact fixed distance.'},{heading:'Make the steps memorable',body:'If you are already aiming for 10,000 steps, The Chaos Walk turns that familiar target into a shared event with two different shoes, one Chaos Fan and city challenges.'}]},
'how-long-to-walk-10000-steps':{title:'How Long Does It Take to Walk 10,000 Steps?',description:'A practical guide to how long 10,000 steps can take at different walking speeds.',intro:'For many people, 10,000 steps takes around 1.5 to 2 hours of active walking, though pace, stride and stops can shift the total.',sections:[{heading:'Typical walking time',body:'A steady recreational pace often puts 10,000 steps somewhere around ninety minutes to two hours of active walking.'},{heading:'Why your time may differ',body:'Walking speed, stride length, hills, crowds, breaks and mobility needs all affect the result. There is no required race pace for PlanetHike.'},{heading:'Break it up if needed',body:'You can build toward the target in smaller walking blocks while training. The event itself is designed around social challenge moments, not continuous speed.'},{heading:'The Chaos Walk takes longer on purpose',body:'Chaos Drops, fan shots and city interactions are part of the experience, so event-day elapsed time may be longer than a plain 10,000-step walk.'}]},
'10000-steps-in-km':{title:'10,000 Steps in KM: What Distance Is It?',description:'Estimate how many kilometres 10,000 steps is and understand why stride length changes the result.',intro:'For many adults, 10,000 steps works out to roughly 6.5 to 8 kilometres, depending on stride length and walking style.',sections:[{heading:'A useful estimate',body:'There is no single exact conversion. Many walkers fall somewhere around 6.5 to 8 km for 10,000 steps.'},{heading:'Stride length matters',body:'Longer strides cover more distance per step. Height, pace, terrain and gait all influence the number.'},{heading:'Why PlanetHike uses steps',body:'A step target is easy to understand across countries and does not require a race course measured to competition standards.'},{heading:'From metric to memorable',body:'The Chaos Walk uses 10,000 steps as the base and adds shared challenges, city crews and a distinctive visual ritual.'}]},
'10000-steps-calories':{title:'How Many Calories Does 10,000 Steps Burn?',description:'Understand why calories burned from 10,000 steps vary and what factors matter most.',intro:'Calories burned during 10,000 steps vary widely. Body size, pace, terrain, fitness and walking efficiency all matter.',sections:[{heading:'There is no universal calorie number',body:'Two people can walk the same number of steps and use different amounts of energy. Treat online calorie figures as estimates rather than guarantees.'},{heading:'What changes energy use',body:'Body mass, pace, hills, surface, temperature and duration all influence calorie expenditure.'},{heading:'Use your own device carefully',body:'Wearables can be useful for personal trends, but their calorie estimates are still approximations.'},{heading:'PlanetHike is not a weight-loss programme',body:'The Chaos Walk focuses on participation, fun and connection. It does not promise calorie burn or health outcomes.'}]},
'10k-walk-training-plan':{title:'10K Walk Training Plan for Beginners',description:'A simple progressive 10K walking plan to help beginners prepare comfortably for a longer walk.',intro:'Build gradually, keep most walks comfortable and practise the time on your feet before event day.',sections:[{heading:'Weeks 1–2: establish consistency',body:'Walk three or four times per week at an easy pace. Focus on consistency rather than distance records.'},{heading:'Weeks 3–4: extend one walk',body:'Keep most walks easy and make one weekly walk longer. Increase gradually rather than jumping straight to the full target.'},{heading:'Weeks 5–6: practise event duration',body:'Complete at least one longer walk close to your expected event duration, using the shoes and clothing you plan to wear.'},{heading:'Event week',body:'Reduce volume, stay comfortable and prioritise footwear that is safe even when the two shoes are visually different.'}]},
'walking-challenge-team-names':{title:'Walking Challenge Team Names: 100 Ideas',description:'Ideas for funny, clever and distinctive walking challenge team names.',intro:'The best team names are easy to remember, easy to shout and easy to put on a group chat.',sections:[{heading:'Chaos-style names',body:'Try names such as Sole Rebels, The Wrong Shoes, Step Misfits, Fan Club, Off Colour Crew, Ten-K Trouble, The Unmatched and Walk This Weird.'},{heading:'Workplace names',body:'Ideas include Meeting Escape Plan, Out of Office, Step Department, Walking Capital, The Pace Makers and 10KPI.'},{heading:'Friends and family names',body:'Try Sole Mates, The Wander List, Family Footwork, Step Siblings, The Long Way Round and Miles of Smiles.'},{heading:'Make your own',body:'Combine a local reference, an inside joke and a walking word. Shorter names usually work better on signs, shirts and social posts.'}]},
'walking-challenge-ideas':{title:'Walking Challenge Ideas That Are Actually Fun',description:'Fresh walking challenge ideas for groups, workplaces and communities.',intro:'A walking challenge becomes more memorable when the route contains moments people want to talk about—not just a step counter.',sections:[{heading:'Add timed challenge drops',body:'Reveal small tasks at set milestones so the route changes character as people progress.'},{heading:'Use a visual signature',body:'A simple shared object or dress rule makes photographs recognisable across different groups and cities.'},{heading:'Build in social interaction',body:'Use safe prompts that encourage participants to make someone smile, create a group pose or invent a team ritual.'},{heading:'End with a shared finish ritual',body:'A common final moment makes the event feel complete and gives every group a recognisable piece of content to share.'}]},
'how-to-organize-a-charity-walk':{title:'How to Organize a Charity Walk',description:'A practical framework for planning a charity walk with a clear cause, route, volunteers and transparent funding model.',intro:'A strong charity walk needs more than a route: define the cause, participant promise, money flow, safety ownership and local operations before promotion begins.',sections:[{heading:'Define the participant proposition',body:'Be clear about why someone would attend even before the cause is explained. The experience itself should be understandable and desirable.'},{heading:'Make the funding model explicit',body:'State exactly how money is generated, what portion supports the cause and how transfers will be reported.'},{heading:'Assign local operational ownership',body:'Each location needs a named lead, volunteer roles, route responsibility, safety planning and participant communication.'},{heading:'Publish proof after the event',body:'Report participation, funds committed, partner transfers and what the supported organisations did with the contribution where available.'}]},
'how-to-start-a-walking-group':{title:'How to Start a Walking Group',description:'Start a local walking group with a clear purpose, meeting rhythm and simple participation rules.',intro:'The easiest walking groups to sustain are simple: one clear meeting point, one predictable rhythm and one reason people want to return.',sections:[{heading:'Choose the purpose',body:'Decide whether the group is social, fitness-focused, exploratory, event-based or mixed. A clear identity helps the right people join.'},{heading:'Keep logistics simple',body:'Use a consistent meeting point, realistic route length and a clear bad-weather or cancellation rule.'},{heading:'Design for newcomers',body:'State pace expectations, accessibility limits and whether people can join alone. Newcomers should not need insider knowledge.'},{heading:'Create a recurring ritual',body:'A distinctive recurring moment, challenge or object can turn a generic walk into something people identify with.'}]},
'walking-scavenger-hunt':{title:'Walking Scavenger Hunt Ideas for Groups',description:'Walking scavenger hunt ideas that add observation, teamwork and playful challenge moments to a route.',intro:'A walking scavenger hunt works best when prompts are simple, safe and easy to verify without distracting people from traffic or the route.',sections:[{heading:'Photo prompts',body:'Find a colour, a shape, a local landmark or a creative group pose. Avoid tasks that require entering private property or unsafe areas.'},{heading:'People prompts',body:'Use low-pressure social tasks such as making someone in your own group laugh or creating a team fan wave.'},{heading:'Milestone prompts',body:'Attach one challenge to a route milestone rather than overwhelming participants with a long checklist.'},{heading:'How this relates to Chaos Drops',body:'PlanetHike uses a related idea: selected challenge moments appear along the 10,000-step experience, while some remain surprise drops until close to event day.'}]}
};

export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const g=guides[slug];if(!g)return{};return{title:`${g.title} | PlanetHike`,description:g.description,alternates:{canonical:`/guides/${slug}`}};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const g=guides[slug];if(!g)notFound();return <SeoLanding eyebrow="PLANETHIKE WALKING GUIDE" title={g.title} intro={g.intro} sections={g.sections} faq={g.faq} ctaLabel="Join The Chaos Walk free"/>;}
