create table if not exists public.planethike_preregistrations (
  id bigint generated by default as identity primary key,
  first_name text not null check (char_length(first_name) between 1 and 80),
  email text not null unique,
  location text not null check (char_length(location) between 1 and 120),
  interest text not null default 'walker' check (interest in ('walker', 'host', 'team')),
  source text not null default 'planethike.org',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.planethike_preregistrations enable row level security;

revoke all on table public.planethike_preregistrations from anon, authenticated;

create or replace function public.set_planethike_prereg_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_planethike_prereg_updated_at on public.planethike_preregistrations;
create trigger trg_planethike_prereg_updated_at
before update on public.planethike_preregistrations
for each row execute function public.set_planethike_prereg_updated_at();

create index if not exists planethike_preregistrations_created_at_idx
  on public.planethike_preregistrations (created_at desc);

create index if not exists planethike_preregistrations_interest_idx
  on public.planethike_preregistrations (interest);
